# Generated by Django 5.1.1 on 2024-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('animal', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000, null=True)),
                ('file_path', models.TextField(null=True)),
            ],
        ),
    ]
