[project]
name = "logfire-django-cat-bacon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.1",
    "openai>=1.44.1",
    "httpx>=0.27.2",
    "psycopg>=3.2.1",
]
